api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity/'
            - '%kernel.project_dir%/src/Users/Domain/Entity/'
            - '%kernel.project_dir%/src/Categories/Domain/Entity/'
            - '%kernel.project_dir%/src/Books/Domain/Entity/'
    formats:        
        json: ['application/json']   
        jsonld: ['application/ld+json']     
    defaults:    
        pagination_enabled: true
        pagination_items_per_page: 100
        pagination_maximum_items_per_page: 100
        stateless: false
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
        vary: ['Content-Type', 'Authorization', 'Origin']
        normalization_context:
            groups: 
                - ['user'] 
                - ['category']
                - ['book']                

        denormalization_context:
            groups: 
                - ['user']
                - ['category']
                - ['book']
                  
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        App\Application\Exception\NotFoundException: 404
        App\Application\Exception\UnauthorizedException: 401