api.books.post:
  path: /api/books
  controller: App\Books\UI\Controller\BookController::record
  methods: [POST]

api.books.alls:
  path: /api/allBooks
  controller: App\Books\UI\Controller\BookController::Alls
  methods: [GET]

api.books.detail:
  path: /api/allBooks/{id}
  controller: App\Books\UI\Controller\BookController::detail
  methods: [GET]



api.books.user:
  path: /api/userBooks
  controller: App\Books\UI\Controller\BookController::getPersonnalBooks
  methods: [GET]

api.books.delete:
  path: /api/deleteBook/{id}
  controller: App\Books\UI\Controller\BookController::delete
  methods: [DELETE]

api.books.unavailable:
  path: /api/unavailableBook/{id}
  controller: App\Books\UI\Controller\BookController::toBeUnavailable
  methods: [PATCH]

api.books.changeStock:
  path: /api/updateStock/{id}/{quantity}
  controller: App\Books\UI\Controller\BookController::toUpdateStock
  methods: [PATCH]

api.books.authors:
  path: /api/authors
  controller: App\Books\UI\Controller\BookController::getAllAuthorNames
  methods: [GET]

api.books.author:
  path: /api/authorNamesByUser
  controller: App\Books\UI\Controller\BookController::getAuthorNamesByUser
  methods: [GET]

