category.list.alls:
  path: /api/categories
  controller: App\Categories\UI\Controller\CategoryController::listAll
  methods: [GET]


category.add:
  path: /api/categories/add
  controller: App\Categories\UI\Controller\CategoryController::add
  methods: [POST]