api.orders.post:
  path: /api/recordOrder
  controller: App\Orders\UI\Controller\OrderController::recordOrder
  methods: [POST]

orders.list.alls:
  path: /admin/order/alls/{page}/{nbre}
  controller: App\Orders\UI\Controller\OrderController::indexAlls
  defaults:
      page: 1
      nbre: 20
  methods: [GET]

orders.cancel:
  path: /admin/order/cancel/{id}
  controller: App\Orders\UI\Controller\cancelOrder
  methods: [GET, POST]

orders.details:
  path: /admin/order/details/{id}
  controller: App\Orders\UI\Controller\OrderController::details
  requirements:
    id: '\d+'    #entier positif
  methods: [GET]

orderItems.details:
  path: /admin/orderItem/details/{id}
  controller: App\Orders\UI\Controller\OrderController::detailsOrderItem
  requirements:
    id: '\d+'    #entier positif
  methods: [GET]




  






