api.orders.post:
  path: /api/recordOrder
  controller: App\Orders\UI\Controller\OrderController::recordOrder
  methods: [POST]

api.seller.accept.orderItem:
  path: /api/seller/orderItems/{id}/accept
  controller: App\Orders\UI\Controller\SellerOrderItemController::accept
  methods: [POST]

api.seller.refuse.orderItem:
  path: /api/seller/orderItems/{id}/refuse
  controller: App\Orders\UI\Controller\SellerOrderItemController::refuse
  methods: [POST]





